---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check Java can running
    command:
      cmd: "java -version"
    environment:
      PATH: "$PATH:/opt/jdk/openjdk-11/bin"
    changed_when: false
