---
- name: Upload .tar.gz file containing binaries from local storage
  copy:
    src: "{{ jdk_distr_name }}"
    dest: "/tmp/jdk-{{ jdk_distr_name }}"
    mode: 0755
  register: download_java_local_binaries
  until: download_java_local_binaries is succeeded
  when: jdk_distr_type == 'local'
- name: Upload .tar.gz file conaining binaries from remote storage
  get_url:
    url: "{{ jdk_url }}"
    dest: "/tmp/jdk-{{ jdk_distr_name }}"
    mode: 0755
  register: download_java_remote_binaries
  until: download_java_remote_binaries is succeeded
  when: jdk_distr_type == 'remote'
- name: Ensure installation dir exists
  become: true
  file:
    state: directory
    path: "{{ java_home }}"
    mode: 0755
- name: Extract java in the installation directory
  become: true
  unarchive:
    copy: false
    src: "/tmp/jdk-{{ jdk_distr_name }}"
    dest: "{{ java_home }}"
    extra_opts: [--strip-components=1]
    creates: "{{ java_home }}/bin/java"
  tags: skip_ansible_lint
- name: Export environment variables
  become: true
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh
    mode: 0755